name: OWASP Dependency-Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Dependency-Check data
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependency-check
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven (skip tests)
        run: mvn -B package --file pom.xml -DskipTests

      - name: Install OWASP Dependency-Check CLI
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip dependency-check-12.1.0-release.zip -d $HOME/dc

      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          $HOME/dc/dependency-check/bin/dependency-check.sh \
            --project "Secure_Password_Manager" \
            --scan . \
            --format HTML \
            --out reports \
            --disableAssembly \
            --nvdApiKey "$NVD_API_KEY" \
            --data ~/.cache/dependency-check \
          || true

      - name: Upload Dependency-Check report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
