name: Snyk Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Java version from pom.xml
        id: extract_java_version
        run: |
          JAVA_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='properties']/*[local-name()='maven.compiler.source']/text()" pom.xml 2>/dev/null || echo "17")
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check vulnerabilities (only pom.xml)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=pom.xml

      # Opcional: monitorar o projeto no painel Snyk (gera histórico e dashboards)
      - name: Snyk monitor (optional)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --file=pom.xml
